# -*- coding: utf-8 -*-
"""b4-mini-project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lN4gkd-deQw740NWz-dXk_bqNgsyKYZJ

**Project Title: Smart Health Tracker Insights**

This project explores data collected from wearable fitness devices to uncover meaningful health patterns and deliver personalized wellness recommendations. The dataset comprises 30,000 entries with features including age, gender, daily steps, heart rates, hours of sleep, calorie intake, stress levels, sleep quality, activity types, and mood. Through this data, we aim to apply regression to predict sleep and calorie metrics, classification to understand mood and stress, clustering to identify user behavior patterns, and time series analysis to observe trends over time. The project combines statistical analysis and machine learning to enable data-informed health interventions.

**Details:**
* Minor in AI
* Batch 4
* Mini Project - Module A and B

**Download the data from:**
https://drive.google.com/file/d/15RtFohMLHMCzPaMFv7nfA2xu8R5mbgff/view?usp=sharing

**Data Set Decription:**

* Age
* Gender
* Daily Steps
* Resting Heart Rate
* Active Heart Rate
* Hours of Sleep
* Daily Calorie Intake
* Stress Level (0-10 scale)
* Sleep Quality (0-100 score)
* Daily Activity Type (categorical: sedentary, moderate, intense)
* Mood (multiclass: sad, neutral, happy)
"""

# Reset float display format to default
# pd.reset_option('display.float_format')

# Load the data
import pandas as pd
df = pd.read_csv(r"C:\Users\Lenovo\Downloads\smart_health_tracker_data (1).csv")
print(df.head())

import pandas as pd

# Calculate percentage of missing values per column
missing_percent = df.isnull().mean() * 100

# Display
print(missing_percent.sort_values())

# Fill the missing values

# Fill numerical features
df['Age'] = df['Age'].fillna(df['Age'].median())
df['Daily_Steps'] = df['Daily_Steps'].fillna(df['Daily_Steps'].mean())
df['Resting_Heart_Rate'] = df['Resting_Heart_Rate'].fillna(df['Resting_Heart_Rate'].median())
df['Active_Heart_Rate'] = df['Active_Heart_Rate'].fillna(df['Active_Heart_Rate'].mean())
df['Hours_of_Sleep'] = df['Hours_of_Sleep'].fillna(df['Hours_of_Sleep'].mean())
df['Daily_Calorie_Intake'] = df['Daily_Calorie_Intake'].fillna(df['Daily_Calorie_Intake'].mean())
df['Sleep_Quality'] = df['Sleep_Quality'].fillna(df['Sleep_Quality'].mean())

# Fill ordinal/categorical features with mode
df['Gender'] = df['Gender'].fillna(df['Gender'].mode()[0])
df['Stress_Level'] = df['Stress_Level'].fillna(df['Stress_Level'].mode()[0])
df['Daily_Activity_Type'] = df['Daily_Activity_Type'].fillna(df['Daily_Activity_Type'].mode()[0])
df['Mood'] = df['Mood'].fillna(df['Mood'].mode()[0])

print(df.head())

# Visualize the tracker data
import matplotlib.pyplot as plt

# Set plot style
plt.style.use('seaborn-v0_8-whitegrid')

# Create figure and axes
fig, axes = plt.subplots(nrows=6, ncols=2, figsize=(16, 24))
axes = axes.flatten()

# Plot 1 - Age (histogram)
axes[0].hist(df['Age'], bins=15, color='lightcoral', edgecolor='black')
axes[0].set_title('Age Distribution')

# Plot 2 - Gender (bar plot)
df['Gender'].value_counts().plot(kind='bar', ax=axes[1], color='teal')
axes[1].set_title('Gender Count')

# Plot 3 - Daily Steps (histogram)
axes[2].hist(df['Daily_Steps'], bins=20, color='dodgerblue', edgecolor='black')
axes[2].set_title('Daily Steps Distribution')

# Plot 4 - Resting Heart Rate (boxplot)
axes[3].boxplot(df['Resting_Heart_Rate'])
axes[3].set_title('Resting Heart Rate')

# Plot 5 - Active Heart Rate (boxplot)
axes[4].boxplot(df['Active_Heart_Rate'])
axes[4].set_title('Active Heart Rate')

# Plot 6 - Hours of Sleep (histogram)
axes[5].hist(df['Hours_of_Sleep'], bins=10, color='mediumseagreen', edgecolor='black')
axes[5].set_title('Hours of Sleep')

# Plot 7 - Calorie Intake (histogram)
axes[6].hist(df['Daily_Calorie_Intake'], bins=20, color='orange', edgecolor='black')
axes[6].set_title('Daily Calorie Intake')

# Plot 8 - Stress Level (bar plot)
df['Stress_Level'].value_counts().sort_index().plot(kind='bar', ax=axes[7], color='orchid')
axes[7].set_title('Stress Level (0–10)')

# Plot 9 - Sleep Quality (histogram)
axes[8].hist(df['Sleep_Quality'], bins=10, color='slateblue', edgecolor='black')
axes[8].set_title('Sleep Quality Score')

# Plot 10 - Activity Type (bar plot)
df['Daily_Activity_Type'].value_counts().plot(kind='bar', ax=axes[9], color='goldenrod')
axes[9].set_title('Activity Type Distribution')

# Plot 11 - Mood (bar plot)
df['Mood'].value_counts().plot(kind='bar', ax=axes[10], color='lightgreen')
axes[10].set_title('Mood Distribution')

# Remove last unused subplot
fig.delaxes(axes[11])

# Adjust layout
plt.tight_layout()
plt.show()

"""Objective: Predict Hours of Sleep

**Hypothesis (for Hours of Sleep):**

H₀ (Null): There is no significant relationship between daily steps, stress level and hours of sleep.

H₁ (Alternative): There is significant relationship between daily steps, stress level and hours of sleep.

We are testing whether features like daily steps or stress level predict hours of sleep.

Two-tailed test - Because we are open to the effect being either positive or negative (e.g., stress might increase or decrease sleep).
"""

import statsmodels.api as sm

data = df[['Daily_Steps', 'Stress_Level', 'Hours_of_Sleep']]

# Define independent variables (X) and dependent variable (y)
X = data[['Daily_Steps', 'Stress_Level']]
y = data['Hours_of_Sleep']

# Add constant to X (for intercept)
X = sm.add_constant(X)

# Fit the model
model = sm.OLS(y, X).fit()

# Print summary
print(model.summary())

import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_squared_error
import matplotlib.pyplot as plt
import seaborn as sns

# Define features and target
X = df[['Daily_Steps', 'Stress_Level']]
y = df['Hours_of_Sleep']

# Fit the model
model = LinearRegression()
model.fit(X, y)

# Predict
y_pred = model.predict(X)

# Print regression info
print("Intercept:", model.intercept_)
print("Coefficient (Daily Steps):", model.coef_[0])
print("Coefficient (Stress Level):", model.coef_[1])
print("R² Score:", r2_score(y,y_pred))

# Plot 1: Daily Steps vs Hours of Sleep
sns.lmplot(x='Daily_Steps', y='Hours_of_Sleep', data=df, scatter_kws={'alpha': 0.3})
plt.title('Daily Steps vs Hours of Sleep')
plt.xlabel('Daily Steps')
plt.ylabel('Hours of Sleep')
plt.show()

# Plot 2: Stress Level vs Hours of Sleep
sns.lmplot(x='Stress_Level', y='Hours_of_Sleep', data=df, scatter_kws={'alpha': 0.3})
plt.title('Stress Level vs Hours of Sleep')
plt.xlabel('Stress Level')
plt.ylabel('Hours of Sleep')
plt.show()

# Get all the correlation with sleep
import pandas as pd

# Correlation with sleep
correlations = df.corr(numeric_only=True)['Stress_Level'].sort_values(ascending=False)
print(correlations)

"""**Hypothesis Testing**

Target (y): Sleep_Quality

Feature (x): Stress_Level

**Hypotheses:**

H₀ (Null Hypothesis): There is no significant linear relationship between stress level and sleep quality

H₁ (Alternative Hypothesis): There is significant linear relationship between stress level and sleep quality




"""

import statsmodels.api as sm
import pandas as pd

# Define X and y
X = df[['Stress_Level']]
y = df['Sleep_Quality']

# Add constant (intercept term)
X = sm.add_constant(X)

# Fit OLS model
model = sm.OLS(y, X).fit()

# Print summary for hypothesis test
print(model.summary())

import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_squared_error
import matplotlib.pyplot as plt
import seaborn as sns

# Prepare data
X = df[['Stress_Level']]
y = df['Sleep_Quality']

# Fit model
model = LinearRegression()
model.fit(X, y)

# Predict
y_pred = model.predict(X)

# Print regression info
print("Intercept:", model.intercept_)
print("Coefficient (Stress Level):", model.coef_[0])
print("R² Score:", r2_score(y, y_pred))
print("MSE:", mean_squared_error(y, y_pred))

# Plot regression line
plt.figure(figsize=(8,5))
sns.regplot(x='Stress_Level', y='Sleep_Quality', data=df, scatter_kws={'alpha':0.3})
plt.title('Linear Regression: Stress Level vs Sleep Quality')
plt.xlabel('Stress Level')
plt.ylabel('Sleep Quality')
plt.grid(True)
plt.show()

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.preprocessing import StandardScaler

# Binary target: Well Rested
df['Well_Rested'] = (df['Hours_of_Sleep'] >= 7).astype(int)

# Features and target
X = df[['Sleep_Quality', 'Stress_Level', 'Resting_Heart_Rate']]
y = df['Well_Rested']

# Scale features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Split
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

# Fit a Regression
logreg = LogisticRegression()
logreg.fit(X_train, y_train)
y_pred = logreg.predict(X_test)

# Results
print(classification_report(y_test, y_pred))

from sklearn.svm import SVC
from sklearn.metrics import classification_report
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Binary target: Well Rested
df['Well_Rested'] = (df['Hours_of_Sleep'] >= 7).astype(int)

# Features and target
X = df[['Sleep_Quality', 'Stress_Level', 'Resting_Heart_Rate']]
y = df['Well_Rested']

# Scale features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Train/test split
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

# SVM Classifier with RBF kernel
svm = SVC(kernel='rbf', class_weight='balanced')
svm.fit(X_train, y_train)
y_pred = svm.predict(X_test)

# Evaluation
print(classification_report(y_test, y_pred))

from sklearn.decomposition import PCA
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
import numpy as np

# Prepare data
X = df[['Sleep_Quality', 'Stress_Level', 'Resting_Heart_Rate']]
y = (df['Hours_of_Sleep'] >= 7).astype(int)  # Binary target

# Scale and reduce to 2D
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

pca=PCA(n_components=2)
X_pca = pca.fit_transform(X_scaled)

# Train/test split
X_train, X_test, y_train, y_test = train_test_split(X_pca, y, test_size=0.2, random_state=42)

# Train SVM
svm = SVC(kernel='rbf', class_weight='balanced')
svm.fit(X_train, y_train)

# Create meshgrid for decision surface
x_min, x_max = X_pca[:, 0].min() - 1, X_pca[:, 0].max() + 1
y_min, y_max = X_pca[:, 1].min() - 1, X_pca[:, 1].max() + 1
xx, yy = np.meshgrid(np.linspace(x_min, x_max, 300),
                     np.linspace(y_min, y_max, 300))

Z = svm.predict(np.c_[xx.ravel(), yy.ravel()])
Z = Z.reshape(xx.shape)

# Plot
plt.figure(figsize=(8, 6))
plt.contourf(xx, yy, Z, cmap=plt.cm.coolwarm, alpha=0.3)
plt.scatter(X_pca[:, 0], X_pca[:, 1], c=y, cmap=plt.cm.coolwarm, s=10, edgecolors='k')
plt.title("SVM Decision Boundary with PCA")
plt.xlabel("PCA Component 1")
plt.ylabel("PCA Component 2")
plt.grid(True)
plt.show()

# What do we learn from this?

from sklearn.svm import SVC
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

# Encode the target
le = LabelEncoder()
df['Activity_encoded'] = le.fit_transform(df['Daily_Activity_Type'])  # sedentary=0, moderate=1, intense=2

# Features that influence activity clearly
X = df[['Daily_Steps', 'Active_Heart_Rate', 'Daily_Calorie_Intake']]
y = df['Activity_encoded']

# Scale features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Train/test split
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

# Train SVM
svm = SVC(kernel='rbf', class_weight='balanced')
svm.fit(X_train, y_train)
y_pred = svm.predict(X_test)

# Results
print(classification_report(y_test, y_pred, target_names=le.classes_))

# Experimenting with Kernels

import pandas as pd
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import classification_report

# Step 1: Encode target labels (Daily_Activity_Type)
df['Daily_Activity_Type'] = df['Daily_Activity_Type'].str.strip().str.lower()
le = LabelEncoder()
df['Activity_Label'] = le.fit_transform(df['Daily_Activity_Type'])

print("Activity Type Mapping:", dict(zip(le.classes_, le.transform(le.classes_))))

# Step 2: Select relevant features and target
features = ['Daily_Calorie_Intake']
X = df[features]
y = df['Activity_Label']

# Step 3: Scale features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Step 4: Train-test split
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42, stratify=y)

# Step 5: Train SVM with different kernel
svm_model = SVC(kernel='sigmoid', class_weight='balanced')
svm_model.fit(X_train, y_train)

# Step 6: Predict and evaluate
y_pred = svm_model.predict(X_test)
print("\nClassification Report:\n")
print(classification_report(y_test, y_pred, target_names=le.classes_))

# Understanding Daily Calorie Intake
import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(8, 4))
sns.boxplot(x=df['Daily_Calorie_Intake'], color='skyblue')

plt.title('Boxplot of Daily Calorie Intake')
plt.xlabel('Daily Calorie Intake')
plt.grid(axis='x', linestyle='--', alpha=0.5)
plt.tight_layout()
plt.show()

# Mapping to daily activities

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(10, 6))
sns.boxplot(x='Daily_Activity_Type', y='Daily_Calorie_Intake', data=df)

plt.title('Daily Calorie Intake by Activity Type')
plt.xlabel('Activity Type')
plt.ylabel('Daily Calorie Intake')
plt.grid(axis='y', linestyle='--', alpha=0.5)
plt.tight_layout()
plt.show()

# Stress Level and Sleep Quality
import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(8, 5))
sns.scatterplot(x='Stress_Level', y='Sleep_Quality', hue='Mood', data=df)
plt.title('Stress Level vs Sleep Quality by Mood')
plt.grid(True)
plt.tight_layout()
plt.show()

# Pair Plots
sns.pairplot(df[['Sleep_Quality', 'Stress_Level', 'Hours_of_Sleep', 'Mood']], hue='Mood')
plt.suptitle('Pairwise Relationships', y=1.02)
plt.show()

# Heatmap
plt.figure(figsize=(10, 8))
sns.heatmap(df.corr(numeric_only=True), annot=True, cmap='coolwarm', fmt=".2f")
plt.title('Correlation Matrix of Numeric Features')
plt.tight_layout()
plt.show()

sns.scatterplot(x='Daily_Steps', y = 'Daily_Calorie_Intake', data=df)
plt.title('Daily Steps vs Calorie Intake')
plt.show()

# Applying k-means

import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
import matplotlib.pyplot as plt
import seaborn as sns

# Step 1: Select features
features = ['Hours_of_Sleep', 'Sleep_Quality', 'Stress_Level']
X = df[features]

# Step 2: Scale features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Step 3: Apply KMeans
kmeans = KMeans(n_clusters=8, random_state=4)
labels = kmeans.fit_predict(X_scaled)

# Step 4: Silhouette score
score = silhouette_score(X_scaled, labels)
print(f"Silhouette Score: {score:.2f}")

# Step 5: Visualize first two features (as a simple projection)
plt.figure(figsize=(8, 6))
sns.scatterplot(x=X_scaled[:, 0], y=X_scaled[:, 1], hue=labels, palette='Set2', s=50)
plt.title("KMeans Clusters")
plt.xlabel(features[0])
plt.ylabel(features[1])
plt.grid(True)
plt.show()

from sklearn.preprocessing import StandardScaler
from sklearn.cluster import DBSCAN
import matplotlib.pyplot as plt
import seaborn as sns

# Select features
X = df[['Daily_Steps', 'Daily_Calorie_Intake']]

# Scale
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Apply DBSCAN
db = DBSCAN(eps=0.04, min_samples=20)
labels = db.fit_predict(X_scaled)

# Count noise points
n_noise = sum(labels == -1)
n_clusters = len(set(labels)) - (1 if -1 in labels else 0)

print(f"DBSCAN found {n_clusters} clusters and {n_noise} noise points")

# Plot
plt.figure(figsize=(8, 6))
sns.scatterplot(x=X_scaled[:, 0], y=X_scaled[:, 1], hue=labels, palette='Set2', legend='full', s=50)
plt.title("DBSCAN Clustering on Steps vs. Calorie Intake")
plt.xlabel("Daily Steps (scaled)")
plt.ylabel("Calorie Intake (scaled)")
plt.grid(True)
plt.show()

"""When to use the respective metrics

| Metric    | Best For                              |
| --------- | ------------------------------------- |
| Accuracy  | Balanced classes, equal error cost    |
| Precision | False positives are worse (be exact)  |
| Recall    | False negatives are worse (catch all) |
| F1 Score  | Balance when classes are imbalanced   |

"""

# lets us balance it!

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

# Create binary label: Well Rested
df['Well_Rested'] = (df['Hours_of_Sleep'] >= 4).astype(int)

# Select features and target
X = df[['Sleep_Quality', 'Stress_Level', 'Daily_Steps', 'Daily_Calorie_Intake']]
y = df['Well_Rested']

# Scale features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

# Fit model
model = LogisticRegression(class_weight='balanced')
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

# Classification report (optional)
print(classification_report(y_test, y_pred))

# Confusion Matrix
cm = confusion_matrix(y_test, y_pred)
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=['Not Rested', 'Well Rested'])
disp.plot(cmap='Blues')
plt.title('Confusion Matrix')
plt.show()

# Do we need a cross validation?

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import StandardScaler
import numpy as np

# Define features and target
X = df[['Sleep_Quality', 'Stress_Level', 'Daily_Steps', 'Daily_Calorie_Intake']]
y = (df['Hours_of_Sleep'] >= 7).astype(int)  # Binary target: Well Rested

# Scale features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Define the model
model = LogisticRegression(class_weight='balanced')

# Perform 5-fold cross-validation
f1_scores = cross_val_score(model, X_scaled, y, cv=5, scoring='f1')

# Print scores
print("F1 Scores (5-Fold):", f1_scores)
print("Mean F1 Score:", np.mean(f1_scores))

"""**Fill in the blanks: **


1. _________ is used to scale features so they have a mean of 0 and a standard deviation of 1.
2. To handle class imbalance, we can use the argument class_weight='_________' in models like logistic regression or SVM.
3. The LabelEncoder is used to convert _________ variables into numeric form.
4. In linear regression, the dependent variable is also called the _________.
5. In the model summary, a p-value less than 0.05 usually suggests that the predictor is _________.
6. The F1 score is the harmonic mean of _________ and _________.
7. A confusion matrix compares predicted labels with _________ labels.
8. When a model always predicts the majority class, it may have **high accuracy but low _________.
9. _________-fold cross-validation** helps estimate a model’s generalization ability by training and testing on multiple data splits.
10. The _________ score is used to evaluate how well-separated and dense the clusters are in unsupervised learning.

"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, ConfusionMatrixDisplay, roc_auc_score, roc_curve
)
import matplotlib.pyplot as plt
import seaborn as sns

# Target already defined
df['Well_Rested'] = (df['Hours_of_Sleep'] >= 7).astype(int)

# Feature selection
features = ['Sleep_Quality','Stress_Level','Daily_Calorie_Intake','Active_Heart_Rate','Resting_Heart_Rate']
X = df[features].values
y = df['Well_Rested'].values

# Scale the features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Train/test split
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

# Train Logistic Regression model
model = LogisticRegression(class_weight='balanced')
model.fit(X_train, y_train)

# Predictions
y_pred = model.predict(X_test)
y_prob = model.predict_proba(X_test)[:, 1]

# Evaluation metrics
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred))
print("Recall:", recall_score(y_test, y_pred))
print("F1 Score:", f1_score(y_test, y_pred))
print("ROC AUC Score:", roc_auc_score(y_test, y_prob))

# Confusion Matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=['Not Rested', 'Well Rested'])
disp.plot(cmap='Blues')
plt.title("Confusion Matrix")
plt.show()

# ROC Curve
fpr, tpr, _ = roc_curve(y_test, y_prob)
plt.figure(figsize=(6, 4))
plt.plot(fpr, tpr, label=f"AUC = {roc_auc_score(y_test, y_prob):.2f}", color='darkorange')
plt.plot([0, 1], [0, 1], linestyle='--', color='navy')
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve")
plt.legend()
plt.grid()
plt.show()

# Probability distribution
plt.figure(figsize=(6, 4))
sns.histplot(y_prob, bins=30, kde=True, color='green')
plt.title("Predicted Probability Distribution")
plt.xlabel("Probability of Being Well Rested")
plt.ylabel("Frequency")
plt.show()

import torch
import torch.nn as nn
import torch.optim as optim
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score, f1_score,
    confusion_matrix, roc_auc_score, ConfusionMatrixDisplay, roc_curve
)

# Define target
df['Well_Rested'] = (df['Hours_of_Sleep'] >= 7).astype(int)

# Features
features = ['Sleep_Quality','Stress_Level','Daily_Calorie_Intake','Active_Heart_Rate','Resting_Heart_Rate']
X = df[features].values
y = df['Well_Rested'].values

# Scale features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

# Torch tensors
X_train = torch.tensor(X_train, dtype=torch.float32)
X_test = torch.tensor(X_test, dtype=torch.float32)
y_train = torch.tensor(y_train, dtype=torch.float32).view(-1, 1)
y_test = torch.tensor(y_test, dtype=torch.float32).view(-1, 1)

# Model with 5 input features
class Perceptron(nn.Module):
    def __init__(self):
        super(Perceptron, self).__init__()
        self.fc = nn.Linear(5, 1)

    def forward(self, x):
        return torch.sigmoid(self.fc(x))

model = Perceptron()
criterion = nn.BCELoss()
optimizer = optim.Adam(model.parameters(), lr=0.01)

# Training
for epoch in range(100):
    model.train()
    optimizer.zero_grad()
    output = model(X_train)
    loss = criterion(output, y_train)
    loss.backward()
    optimizer.step()
    if epoch % 10 == 0:
        print(f"Epoch {epoch}, Loss: {loss.item():.4f}")

# Evaluation
model.eval()
with torch.no_grad():
    y_pred_prob = model(X_test)
    y_pred = (y_pred_prob >= 0.5).float()

# Convert to numpy
y_true = y_test.numpy()
y_pred_np = y_pred.numpy()
y_prob_np = y_pred_prob.numpy()

# Metrics
print("\nEvaluation Metrics:")
print("Accuracy:", accuracy_score(y_true, y_pred_np))
print("Precision:", precision_score(y_true, y_pred_np))
print("Recall:", recall_score(y_true, y_pred_np))
print("F1 Score:", f1_score(y_true, y_pred_np))
print("ROC AUC Score:", roc_auc_score(y_true, y_prob_np))

# Confusion Matrix
cm = confusion_matrix(y_true, y_pred_np)
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=['Not Rested', 'Well Rested'])
disp.plot(cmap='Blues')
plt.title("Confusion Matrix")
plt.show()

# ROC Curve
fpr, tpr, _ = roc_curve(y_true, y_prob_np)
plt.figure(figsize=(6, 4))
plt.plot(fpr, tpr, color='darkorange', label=f'ROC Curve (AUC = {roc_auc_score(y_true, y_prob_np):.2f})')
plt.plot([0, 1], [0, 1], color='navy', linestyle='--')
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve")
plt.legend(loc="lower right")
plt.grid()
plt.show()

# Probability Histogram
plt.figure(figsize=(6, 4))
sns.histplot(y_prob_np, bins=30, kde=True, color='purple')
plt.title("Distribution of Predicted Probabilities")
plt.xlabel("Probability of Being Well Rested")
plt.ylabel("Count")
plt.show()

import torch
import torch.nn as nn
import torch.optim as optim
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score, f1_score,
    confusion_matrix, ConfusionMatrixDisplay, roc_auc_score, roc_curve
)

# You already have df and missing values are filled
df['Well_Rested'] = (df['Hours_of_Sleep'] >= 7).astype(int)

# Use new feature set
features = ['Sleep_Quality','Stress_Level','Daily_Calorie_Intake','Active_Heart_Rate','Resting_Heart_Rate']
X = df[features].values
y = df['Well_Rested'].values

# Scale features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Split data
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

# Convert to torch tensors
X_train = torch.tensor(X_train, dtype=torch.float32)
X_test = torch.tensor(X_test, dtype=torch.float32)
y_train = torch.tensor(y_train, dtype=torch.float32).view(-1, 1)
y_test = torch.tensor(y_test, dtype=torch.float32).view(-1, 1)

# Neural Network model with ReLU and hidden layers
class NNet(nn.Module):
    def __init__(self):
        super(NNet, self).__init__()
        self.net = nn.Sequential(
            nn.Linear(5,32),
            nn.ReLU(),
            nn.Linear(32,16),
            nn.ReLU(),
            nn.Linear(16,1),
            nn.Sigmoid()
        )

    def forward(self, x):
        return self.net(x)

model = NNet()
criterion = nn.BCELoss()
optimizer = optim.Adam(model.parameters(), lr=0.01)

# Training loop
for epoch in range(100):
    model.train()
    optimizer.zero_grad()
    outputs = model(X_train)
    loss = criterion(outputs, y_train)
    loss.backward()
    optimizer.step()
    if epoch % 10 == 0:
        print(f"Epoch {epoch}, Loss: {loss.item():.4f}")

# Evaluation
model.eval()
with torch.no_grad():
    y_pred_prob = model(X_test)
    y_pred = (y_pred_prob >= 0.5).float()

# Convert to numpy
y_true = y_test.numpy()
y_pred_np = y_pred.numpy()
y_prob_np = y_pred_prob.numpy()

# Metrics
print("\nEvaluation Metrics:")
print("Accuracy:", accuracy_score(y_true, y_pred_np))
print("Precision:", precision_score(y_true, y_pred_np))
print("Recall:", recall_score(y_true, y_pred_np))
print("F1 Score:", f1_score(y_true, y_pred_np))
print("ROC AUC Score:", roc_auc_score(y_true, y_prob_np))

# Confusion Matrix
cm = confusion_matrix(y_true, y_pred_np)
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=['Not Rested', 'Well Rested'])
disp.plot(cmap='Blues')
plt.title("Confusion Matrix")
plt.show()

# ROC Curve
fpr, tpr, _ = roc_curve(y_true, y_prob_np)
plt.figure(figsize=(6, 4))
plt.plot(fpr, tpr, color='darkorange', label=f'ROC Curve (AUC = {roc_auc_score(y_true, y_prob_np):.2f})')
plt.plot([0, 1], [0, 1], color='navy', linestyle='--')
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve")
plt.legend(loc="lower right")
plt.grid()
plt.show()

# Probability Distribution
plt.figure(figsize=(6, 4))
sns.histplot(y_prob_np, bins=30, kde=True, color='purple')
plt.title("Distribution of Predicted Probabilities")
plt.xlabel("Probability of Being Well Rested")
plt.ylabel("Count")
plt.show()

"""Results Comparison

| **Metric**        | **Logistic Regression** | **Perceptron** | **Deep Neural Network** |
| ----------------- | ----------------------- | -------------- | ----------------------- |
| **Accuracy**      | 0.504                   | 0.511          | **0.515**               |
| **Precision**     | 0.515                   | 0.511          | **0.517**               |
| **Recall**        | 0.505                   | **1.000**      | 0.770                   |
| **F1 Score**      | 0.510                   | 0.677          | **0.619**               |
| **ROC AUC Score** | 0.505                   | 0.505          | **0.511**               |


Summary:
Deep NN consistently performs best across most metrics, especially in balanced performance (F1, AUC).

Perceptron has unusually high recall, possibly due to predicting only the positive class.

Logistic Regression is near-random and underperforms the others.


"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, ConfusionMatrixDisplay, roc_auc_score, roc_curve
)
import matplotlib.pyplot as plt
import seaborn as sns

# Target already defined
df['Well_Rested'] = (df['Sleep_Quality'] >=75).astype(int)

# Feature selection
features = ['Hours_of_Sleep','Stress_Level','Daily_Calorie_Intake','Active_Heart_Rate','Resting_Heart_Rate']
X = df[features].values
y = df['Well_Rested'].values

# Scale the features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Train/test split
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

# Train Logistic Regression model
model = LogisticRegression(class_weight='balanced')
model.fit(X_train, y_train)

# Predictions
y_pred = model.predict(X_test)
y_prob = model.predict_proba(X_test)[:, 1]

# Evaluation metrics
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred))
print("Recall:", recall_score(y_test, y_pred))
print("F1 Score:", f1_score(y_test, y_pred))
print("ROC AUC Score:", roc_auc_score(y_test, y_prob))

# Confusion Matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=['Not Rested', 'Well Rested'])
disp.plot(cmap='Blues')
plt.title("Confusion Matrix")
plt.show()

# ROC Curve
fpr, tpr, _ = roc_curve(y_test, y_prob)
plt.figure(figsize=(6, 4))
plt.plot(fpr, tpr, label=f"AUC = {roc_auc_score(y_test, y_prob):.2f}", color='darkorange')
plt.plot([0, 1], [0, 1], linestyle='--', color='navy')
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve")
plt.legend()
plt.grid()
plt.show()

# Probability distribution
plt.figure(figsize=(6, 4))
sns.histplot(y_prob, bins=30, kde=True, color='green')
plt.title("Predicted Probability Distribution")
plt.xlabel("Probability of Being Well Rested")
plt.ylabel("Frequency")
plt.show()

import torch
import torch.nn as nn
import torch.optim as optim
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score, f1_score,
    confusion_matrix, roc_auc_score, ConfusionMatrixDisplay, roc_curve
)

# Define target
df['Well_Rested'] = (df['Sleep_Quality'] >= 75).astype(int)

# Features
features = ['Hours_of_Sleep','Stress_Level','Daily_Calorie_Intake','Active_Heart_Rate','Resting_Heart_Rate']
X = df[features].values
y = df['Well_Rested'].values

# Scale features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

# Torch tensors
X_train = torch.tensor(X_train, dtype=torch.float32)
X_test = torch.tensor(X_test, dtype=torch.float32)
y_train = torch.tensor(y_train, dtype=torch.float32).view(-1, 1)
y_test = torch.tensor(y_test, dtype=torch.float32).view(-1, 1)

# Model with 5 input features
class Perceptron(nn.Module):
    def __init__(self):
        super(Perceptron, self).__init__()
        self.fc = nn.Linear(5, 1)

    def forward(self, x):
        return torch.sigmoid(self.fc(x))

model = Perceptron()
criterion = nn.BCELoss()
optimizer = optim.Adam(model.parameters(), lr=0.01)

# Training
for epoch in range(100):
    model.train()
    optimizer.zero_grad()
    output = model(X_train)
    loss = criterion(output, y_train)
    loss.backward()
    optimizer.step()
    if epoch % 10 == 0:
        print(f"Epoch {epoch}, Loss: {loss.item():.4f}")

# Evaluation
model.eval()
with torch.no_grad():
    y_pred_prob = model(X_test)
    y_pred = (y_pred_prob >= 0.5).float()

# Convert to numpy
y_true = y_test.numpy()
y_pred_np = y_pred.numpy()
y_prob_np = y_pred_prob.numpy()

# Metrics
print("\nEvaluation Metrics:")
print("Accuracy:", accuracy_score(y_true, y_pred_np))
print("Precision:", precision_score(y_true, y_pred_np))
print("Recall:", recall_score(y_true, y_pred_np))
print("F1 Score:", f1_score(y_true, y_pred_np))
print("ROC AUC Score:", roc_auc_score(y_true, y_prob_np))

# Confusion Matrix
cm = confusion_matrix(y_true, y_pred_np)
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=['Not Rested', 'Well Rested'])
disp.plot(cmap='Blues')
plt.title("Confusion Matrix")
plt.show()

# ROC Curve
fpr, tpr, _ = roc_curve(y_true, y_prob_np)
plt.figure(figsize=(6, 4))
plt.plot(fpr, tpr, color='darkorange', label=f'ROC Curve (AUC = {roc_auc_score(y_true, y_prob_np):.2f})')
plt.plot([0, 1], [0, 1], color='navy', linestyle='--')
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve")
plt.legend(loc="lower right")
plt.grid()
plt.show()

# Probability Histogram
plt.figure(figsize=(6, 4))
sns.histplot(y_prob_np, bins=30, kde=True, color='purple')
plt.title("Distribution of Predicted Probabilities")
plt.xlabel("Probability of Being Well Rested")
plt.ylabel("Count")
plt.show()

import torch
import torch.nn as nn
import torch.optim as optim
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score, f1_score,
    confusion_matrix, ConfusionMatrixDisplay, roc_auc_score, roc_curve
)

# You already have df and missing values are filled
df['Well_Rested'] = (df['Sleep_Quality'] >= 75).astype(int)

# Use new feature set
features = ['Hours_of_Sleep','Stress_Level','Daily_Calorie_Intake','Active_Heart_Rate','Resting_Heart_Rate']
X = df[features].values
y = df['Well_Rested'].values

# Scale features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Split data
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

# Convert to torch tensors
X_train = torch.tensor(X_train, dtype=torch.float32)
X_test = torch.tensor(X_test, dtype=torch.float32)
y_train = torch.tensor(y_train, dtype=torch.float32).view(-1, 1)
y_test = torch.tensor(y_test, dtype=torch.float32).view(-1, 1)

# Neural Network model with ReLU and hidden layers
class NNet(nn.Module):
    def __init__(self):
        super(NNet, self).__init__()
        self.net = nn.Sequential(
            nn.Linear(5,32),
            nn.ReLU(),
            nn.Linear(32,16),
            nn.ReLU(),
            nn.Linear(16,1),
            nn.Sigmoid()
        )

    def forward(self, x):
        return self.net(x)

model = NNet()
criterion = nn.BCELoss()
optimizer = optim.Adam(model.parameters(), lr=0.01)

# Training loop
for epoch in range(100):
    model.train()
    optimizer.zero_grad()
    outputs = model(X_train)
    loss = criterion(outputs, y_train)
    loss.backward()
    optimizer.step()
    if epoch % 10 == 0:
        print(f"Epoch {epoch}, Loss: {loss.item():.4f}")

# Evaluation
model.eval()
with torch.no_grad():
    y_pred_prob = model(X_test)
    y_pred = (y_pred_prob >= 0.5).float()

# Convert to numpy
y_true = y_test.numpy()
y_pred_np = y_pred.numpy()
y_prob_np = y_pred_prob.numpy()

# Metrics
print("\nEvaluation Metrics:")
print("Accuracy:", accuracy_score(y_true, y_pred_np))
print("Precision:", precision_score(y_true, y_pred_np))
print("Recall:", recall_score(y_true, y_pred_np))
print("F1 Score:", f1_score(y_true, y_pred_np))
print("ROC AUC Score:", roc_auc_score(y_true, y_prob_np))

# Confusion Matrix
cm = confusion_matrix(y_true, y_pred_np)
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=['Not Rested', 'Well Rested'])
disp.plot(cmap='Blues')
plt.title("Confusion Matrix")
plt.show()

# ROC Curve
fpr, tpr, _ = roc_curve(y_true, y_prob_np)
plt.figure(figsize=(6, 4))
plt.plot(fpr, tpr, color='darkorange', label=f'ROC Curve (AUC = {roc_auc_score(y_true, y_prob_np):.2f})')
plt.plot([0, 1], [0, 1], color='navy', linestyle='--')
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve")
plt.legend(loc="lower right")
plt.grid()
plt.show()

# Probability Distribution
plt.figure(figsize=(6, 4))
sns.histplot(y_prob_np, bins=30, kde=True, color='purple')
plt.title("Distribution of Predicted Probabilities")
plt.xlabel("Probability of Being Well Rested")
plt.ylabel("Count")
plt.show()

"""Result Analysis:


| **Metric**        | **Logistic Regression** | **Perceptron** | **Deep Neural Network** |
| ----------------- | ----------------------- | -------------- | ----------------------- |
| **Accuracy**      | 0.873                   | 0.875          | **0.876**               |
| **Precision**     | 0.841                   | **0.944**      | 0.873                   |
| **Recall**        | **0.895**               | 0.777          | 0.857                   |
| **F1 Score**      | **0.867**               | 0.852          | 0.865                   |
| **ROC AUC Score** | 0.958                   | 0.958          | **0.959**               |


Summary:

Accuracy: All models perform well, with Deep NN slightly leading.

Precision: Perceptron is highest—suggesting fewer false positives.

Recall: Logistic Regression performs best, capturing more true positives.

F1 Score: Logistic Regression narrowly edges out the others, indicating a good balance.

ROC AUC: All models are strong, but Deep NN has the best discrimination ability.
"""

# Using Keras
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score, f1_score,
    confusion_matrix, ConfusionMatrixDisplay, roc_auc_score, roc_curve
)
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam

# Target already defined
df['Well_Rested'] = (df['Sleep_Quality'] >= 75).astype(int)

# Feature selection
features = ['Hours_of_Sleep', 'Stress_Level', 'Daily_Calorie_Intake', 'Resting_Heart_Rate', 'Active_Heart_Rate']
X = df[features].values
y = df['Well_Rested'].values

# Scale the features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Train/test split
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.2, random_state=42
)

# Build the model
model = Sequential([
    Dense(32, input_shape=(5,), activation='relu'),
    Dense(16, activation='relu'),
    Dense(1, activation='sigmoid')
])

model.compile(optimizer=Adam(learning_rate=0.01), loss='binary_crossentropy', metrics=['accuracy'])

# Train the model
history = model.fit(X_train, y_train, epochs=100, batch_size=32, verbose=0)

# Predict
y_prob = model.predict(X_test).flatten()
y_pred = (y_prob >= 0.5).astype(int)

# Metrics
print("\nEvaluation Metrics:")
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred))
print("Recall:", recall_score(y_test, y_pred))
print("F1 Score:", f1_score(y_test, y_pred))
print("ROC AUC Score:", roc_auc_score(y_test, y_prob))

# Confusion Matrix
cm = confusion_matrix(y_test, y_pred)
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=['Not Rested', 'Well Rested'])
disp.plot(cmap='Blues')
plt.title("Confusion Matrix")
plt.show()

# ROC Curve
fpr, tpr, _ = roc_curve(y_test, y_prob)
plt.figure(figsize=(6, 4))
plt.plot(fpr, tpr, label=f"AUC = {roc_auc_score(y_test, y_prob):.2f}", color='darkorange')
plt.plot([0, 1], [0, 1], linestyle='--', color='navy')
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve")
plt.legend()
plt.grid()
plt.show()

# Predicted Probability Distribution
plt.figure(figsize=(6, 4))
sns.histplot(y_prob, bins=30, kde=True, color='purple')
plt.title("Distribution of Predicted Probabilities")
plt.xlabel("Probability of Being Well Rested")
plt.ylabel("Count")
plt.show()

# Exploring Calorie Intake and Daily Steps

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import matplotlib.pyplot as plt
import numpy as np

# Features and target
X = df[['Daily_Calorie_Intake']].values
y = df[['Daily_Steps']].values

# Scale features and target
scaler_x = StandardScaler()
scaler_y = StandardScaler()
X_scaled = scaler_x.fit_transform(X)
y_scaled = scaler_y.fit_transform(y)

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y_scaled, test_size=0.2, random_state=42)

# Train Linear Regression model
model = LinearRegression()
model.fit(X_train, y_train)

# Predict
y_pred_scaled = model.predict(X_test)

# Inverse scale
y_pred = scaler_y.inverse_transform(y_pred_scaled)
y_true = scaler_y.inverse_transform(y_test)

# Evaluation metrics
mae = mean_absolute_error(y_true, y_pred)
rmse = np.sqrt(mean_squared_error(y_true, y_pred))
r2 = r2_score(y_true, y_pred)

print("Evaluation Metrics:")
print(f"MAE  (Mean Absolute Error): {mae:.2f}")
print(f"RMSE (Root Mean Squared Error): {rmse:.2f}")
print(f"R² Score: {r2:.4f}")

# Plot actual vs predicted
plt.scatter(X_test, y_true, label="Actual", color='blue', alpha=0.6)
plt.scatter(X_test, y_pred, label="Predicted", color='red', alpha=0.6)
plt.title("Linear Regression: Daily Calorie Intake vs Daily Steps")
plt.xlabel("Standardized Calorie Intake")
plt.ylabel("Daily Steps")
plt.legend()
plt.grid()
plt.show()

import torch
import torch.nn as nn
import torch.optim as optim
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

# Features and target
X = df[['Daily_Calorie_Intake']].values
y = df[['Daily_Steps']].values

# Scale the data
scaler_x = StandardScaler()
scaler_y = StandardScaler()
X_scaled = scaler_x.fit_transform(X)
y_scaled = scaler_y.fit_transform(y)

# Train-test split
X_train, X_test, y_train, y_test = train_test_split( X_scaled, y_scaled, test_size=0.2, random_state=42
)

# Convert to torch tensors
X_train = torch.tensor(X_train, dtype=torch.float32)
X_test = torch.tensor(X_test, dtype=torch.float32)
y_train = torch.tensor(y_train, dtype=torch.float32)
y_test = torch.tensor(y_test, dtype=torch.float32)

# Define the model
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.net = nn.Sequential(
            nn.Linear(1, 16),
            nn.ReLU(),
            nn.Linear(16, 8),
            nn.ReLU(),
            nn.Linear(8, 1)
        )

    def forward(self, x):
        return self.net(x)

model = Net()
criterion = nn.MSELoss()
optimizer = optim.Adam(model.parameters(), lr=0.01)

# Train the model
for epoch in range(100):
    model.train()
    optimizer.zero_grad()
    output = model(X_train)
    loss = criterion(output, y_train)
    loss.backward()
    optimizer.step()
    if epoch % 10 == 0:
        print(f"Epoch {epoch}, Loss: {loss.item():.4f}")

# Predict
model.eval()
with torch.no_grad():
    y_pred_scaled = model(X_test).numpy()

# Inverse transform
y_pred = scaler_y.inverse_transform(y_pred_scaled)
y_true = scaler_y.inverse_transform(y_test.numpy())

# Evaluation Metrics
mae = mean_absolute_error(y_true, y_pred)
rmse = np.sqrt(mean_squared_error(y_true, y_pred))
r2 = r2_score(y_true, y_pred)

print("\nEvaluation Metrics:")
print(f"MAE  (Mean Absolute Error): {mae:.2f}")
print(f"RMSE (Root Mean Squared Error): {rmse:.2f}")
print(f"R² Score: {r2:.4f}")

# Plot predictions
plt.scatter(X_test.numpy(), y_true, label='Actual', color='blue', alpha=0.6)
plt.scatter(X_test.numpy(), y_pred, label='Predicted', color='red', alpha=0.6)
plt.title("Calorie Intake vs Predicted Daily Steps")
plt.xlabel("Standardized Calorie Intake")
plt.ylabel("Daily Steps")
plt.legend()
plt.grid()
plt.show()